baseURL: https://roderickseow.netlify.app
title: Roderick Seow
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  author: Roderick Seow
  description: Cognitive Psychologist / Data Scientist
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/gohugoio
    - icon: twitter
      name: Twitter
      url: https://twitter.com/gohugoio
security:
  enableInlineShortcodes: false
  exec:
    allow:
    - ^dart-sass-embedded$
    - ^go$
    - ^npx$
    - ^postcss$
    osEnv:
    - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$
  funcs:
    getenv:
    - ^HUGO_
    - BLOGDOWN_POST_RELREF
  http:
    methods:
    - (?i)GET|POST
    urls:
    - .*
markup:
  goldmark:
    renderer:
      unsafe: true
